# Only cover chrome base shortcuts
# I plan to make 1 more generalize for chrome extensions
# n more for every unique webpage that implements shortcuts

# The architecture of this file is based on ADR/0002_extension_config_design.md

version = 1

# --- Application (this entire file represents exactly ONE app id) ---
[app]
id = "chrome"                    # Application ID (unique)
name = "Chrome"                  # Application Name (OS-agnostic)
default_focus_state = "focused"  # For app that only want to run commands that are in focused
default_priority = "Application" # can be OSReserved, GlobalRemapper, OSGlobal, UserOverrides, Application, ApplicationExtensions, DocumentOrWebApp


# application_id + OS -> application_os_name
[app.application_os_name]
windows = "chrome.exe"
macos = "com.google.Chrome"
# linux = "google-chrome"    # optional later

# --- Actions ---
# action_id -> action_name
# action_id + application_id -> action_cmd  (optionally per-OS for portability)
[actions]

[actions.new_tab]
name = "New tab"
focus_state = "focused"
cmd.windows = { mods = ["ctrl"], key = "T" }
cmd.macos = { mods = ["cmd"], key = "T" }

[actions.close_tab]
name = "Close tab"
focus_state = "focused"
cmd.windows = { mods = ["ctrl"], key = "W" }
cmd.macos = { mods = ["cmd"], key = "W" }

[actions.reopen_tab]
name = "Reopen closed tab"
focus_state = "focused"
cmd.windows = { mods = ["ctrl", "shift"], key = "T" }
cmd.macos = { mods = ["cmd", "shift"], key = "T" }
